// <auto-generated />
using System;
using CleanArchMVC.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CleanArchMVC.Infra.Data.Migrations
{
    [DbContext(typeof(CatalogoContext))]
    [Migration("20250922182337_InicioBancoDados")]
    partial class InicioBancoDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CleanArchMVC.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("ID");

                    b.ToTable("categoria", "catalogo");

                    b.HasData(
                        new
                        {
                            ID = new Guid("de666796-44c3-4666-a0e5-c363521e2ead"),
                            Name = "Material Escolar"
                        },
                        new
                        {
                            ID = new Guid("e74d91be-b74a-46a9-972c-6d3c02b480af"),
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            ID = new Guid("60e861ce-0210-4246-a40e-d5b31781a721"),
                            Name = "Acessorios"
                        });
                });

            modelBuilder.Entity("CleanArchMVC.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripion")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("imagem");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<decimal>("Stock")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("produto", "catalogo");
                });

            modelBuilder.Entity("CleanArchMVC.Domain.Entities.Product", b =>
                {
                    b.HasOne("CleanArchMVC.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CleanArchMVC.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
